### ISSUE TITLE
vpnmcast fails with "No such device"

### ISSUE THREAD

**Issue by Abdull** [danielkucera/vpnmcast#2]
After `sudo systemctl start vpnmcast.service` my machine's `/var/log/syslog` has the following log messages:

```
Apr 20 22:23:40 example.com systemd[1]: Started VPN mcast.
Apr 20 22:23:41 example.com vpnmcast[13046]: Exception in thread Thread-1:
Apr 20 22:23:41 example.com vpnmcast[13046]: Traceback (most recent call last):
Apr 20 22:23:41 example.com vpnmcast[13046]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Apr 20 22:23:41 example.com vpnmcast[13046]:     self.run()
Apr 20 22:23:41 example.com vpnmcast[13046]:   File "/opt/vpnmcast/vpnmcast.py", line 93, in run
Apr 20 22:23:41 example.com vpnmcast[13046]:     self.dests[dstif] = self.raw_socket(dstif)
Apr 20 22:23:41 example.com vpnmcast[13046]:   File "/opt/vpnmcast/vpnmcast.py", line 68, in raw_socket
Apr 20 22:23:41 example.com vpnmcast[13046]:     s.setsockopt(socket.SOL_SOCKET, 25, iface+'\0')
Apr 20 22:23:41 example.com vpnmcast[13046]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Apr 20 22:23:41 example.com vpnmcast[13046]:     return getattr(self._sock,name)(*args)
Apr 20 22:23:41 example.com vpnmcast[13046]: error: [Errno 19] No such device
Apr 20 22:23:41 example.com vpnmcast[13046]: Relay started...
Apr 20 22:23:41 example.com systemd[1]: vpnmcast.service: Service hold-off time over, scheduling restart.
Apr 20 22:23:41 example.com systemd[1]: Stopped VPN mcast.
Apr 20 22:23:41 example.com systemd[1]: Started VPN mcast.
Apr 20 22:23:42 example.com vpnmcast[13052]: Exception in thread Thread-1:
Apr 20 22:23:42 example.com vpnmcast[13052]: Traceback (most recent call last):
Apr 20 22:23:42 example.com vpnmcast[13052]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Apr 20 22:23:42 example.com vpnmcast[13052]:     self.run()
Apr 20 22:23:42 example.com vpnmcast[13052]:   File "/opt/vpnmcast/vpnmcast.py", line 93, in run
Apr 20 22:23:42 example.com vpnmcast[13052]:     self.dests[dstif] = self.raw_socket(dstif)
Apr 20 22:23:42 example.com vpnmcast[13052]:   File "/opt/vpnmcast/vpnmcast.py", line 68, in raw_socket
Apr 20 22:23:42 example.com vpnmcast[13052]:     s.setsockopt(socket.SOL_SOCKET, 25, iface+'\0')
Apr 20 22:23:42 example.com vpnmcast[13052]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Apr 20 22:23:42 example.com vpnmcast[13052]:     return getattr(self._sock,name)(*args)
Apr 20 22:23:42 example.com vpnmcast[13052]: error: [Errno 19] No such device
Apr 20 22:23:42 example.com vpnmcast[13052]: Relay started...
Apr 20 22:23:42 example.com systemd[1]: vpnmcast.service: Service hold-off time over, scheduling restart.
Apr 20 22:23:42 example.com systemd[1]: Stopped VPN mcast.
Apr 20 22:23:42 example.com systemd[1]: Started VPN mcast.
Apr 20 22:23:42 example.com vpnmcast[13057]: Exception in thread Thread-1:
Apr 20 22:23:42 example.com vpnmcast[13057]: Traceback (most recent call last):
Apr 20 22:23:42 example.com vpnmcast[13057]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Apr 20 22:23:42 example.com vpnmcast[13057]:     self.run()
Apr 20 22:23:42 example.com vpnmcast[13057]:   File "/opt/vpnmcast/vpnmcast.py", line 93, in run
Apr 20 22:23:42 example.com vpnmcast[13057]:     self.dests[dstif] = self.raw_socket(dstif)
Apr 20 22:23:42 example.com vpnmcast[13057]:   File "/opt/vpnmcast/vpnmcast.py", line 68, in raw_socket
Apr 20 22:23:42 example.com vpnmcast[13057]:     s.setsockopt(socket.SOL_SOCKET, 25, iface+'\0')
Apr 20 22:23:42 example.com vpnmcast[13057]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Apr 20 22:23:42 example.com vpnmcast[13057]:     return getattr(self._sock,name)(*args)
Apr 20 22:23:42 example.com vpnmcast[13057]: error: [Errno 19] No such device
Apr 20 22:23:42 example.com vpnmcast[13057]: Relay started...
Apr 20 22:23:42 example.com systemd[1]: vpnmcast.service: Service hold-off time over, scheduling restart.
Apr 20 22:23:42 example.com systemd[1]: Stopped VPN mcast.
Apr 20 22:23:42 example.com systemd[1]: Started VPN mcast.
Apr 20 22:23:42 example.com vpnmcast[13062]: Exception in thread Thread-1:
Apr 20 22:23:42 example.com vpnmcast[13062]: Traceback (most recent call last):
Apr 20 22:23:42 example.com vpnmcast[13062]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Apr 20 22:23:42 example.com vpnmcast[13062]:     self.run()
Apr 20 22:23:42 example.com vpnmcast[13062]:   File "/opt/vpnmcast/vpnmcast.py", line 93, in run
Apr 20 22:23:42 example.com vpnmcast[13062]:     self.dests[dstif] = self.raw_socket(dstif)
Apr 20 22:23:42 example.com vpnmcast[13062]:   File "/opt/vpnmcast/vpnmcast.py", line 68, in raw_socket
Apr 20 22:23:42 example.com vpnmcast[13062]:     s.setsockopt(socket.SOL_SOCKET, 25, iface+'\0')
Apr 20 22:23:42 example.com vpnmcast[13062]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Apr 20 22:23:42 example.com vpnmcast[13062]:     return getattr(self._sock,name)(*args)
Apr 20 22:23:42 example.com vpnmcast[13062]: error: [Errno 19] No such device
Apr 20 22:23:42 example.com vpnmcast[13062]: Relay started...
Apr 20 22:23:42 example.com systemd[1]: vpnmcast.service: Service hold-off time over, scheduling restart.
Apr 20 22:23:42 example.com systemd[1]: Stopped VPN mcast.
Apr 20 22:23:42 example.com systemd[1]: Started VPN mcast.
Apr 20 22:23:42 example.com vpnmcast[13067]: Exception in thread Thread-1:
Apr 20 22:23:42 example.com vpnmcast[13067]: Traceback (most recent call last):
Apr 20 22:23:42 example.com vpnmcast[13067]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Apr 20 22:23:42 example.com vpnmcast[13067]:     self.run()
Apr 20 22:23:42 example.com vpnmcast[13067]:   File "/opt/vpnmcast/vpnmcast.py", line 93, in run
Apr 20 22:23:42 example.com vpnmcast[13067]:     self.dests[dstif] = self.raw_socket(dstif)
Apr 20 22:23:42 example.com vpnmcast[13067]:   File "/opt/vpnmcast/vpnmcast.py", line 68, in raw_socket
Apr 20 22:23:42 example.com vpnmcast[13067]:     s.setsockopt(socket.SOL_SOCKET, 25, iface+'\0')
Apr 20 22:23:42 example.com vpnmcast[13067]:   File "/usr/lib/python2.7/socket.py", line 228, in meth
Apr 20 22:23:42 example.com vpnmcast[13067]:     return getattr(self._sock,name)(*args)
Apr 20 22:23:42 example.com vpnmcast[13067]: error: [Errno 19] No such device
Apr 20 22:23:42 example.com vpnmcast[13067]: Relay started...
Apr 20 22:23:42 example.com systemd[1]: vpnmcast.service: Service hold-off time over, scheduling restart.
Apr 20 22:23:42 example.com systemd[1]: Stopped VPN mcast.
Apr 20 22:23:42 example.com systemd[1]: vpnmcast.service: Start request repeated too quickly.
Apr 20 22:23:42 example.com systemd[1]: Failed to start VPN mcast.
```

**Comment by danielkucera** [comment]
Hi Abdull. You need to correctly set sourceif and destifs in the script.

**Comment by danielkucera** [comment]
Did it work after that?

**Comment by Abdull** [comment]
Hi Daniel, vpnmcast does not work yet for my purposes - but I'll keep on working on getting it running and will gladly help by trying out solutions.

My scenario is the following:
* I'd like to use UPnP/DLNA in order to connect to my media library from anywhere in the world.
* For this purpose, I've set up an Ubuntu 16.04 LTS machine that is running in the public Internet. On that machine, I installed the UPnP/DLNA daemon *ReadyMedia* (formerly known as *MiniDLNA*).
* As I learned, UPnP/DLNA requires IP multicasting with the *Simple Service Discovery Protocol* on port `1900/udp` and multicast address `239.255.255.250`.
* As `239.255.255.250` multicast UDP datagrams are not routed on the public Internet (for good reasons :), I set up an OpenVPN server on my Ubuntu machine. I followed [DigitalOcean's OpenVPN server setup guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04).
* Connecting OpenVPN clients (Android smartphone and my home computer) with the OpenVPN server still does not show the MiniDNLA-based UPnP server in UPnP-compatible software clients such as *Video LAN Client*.

That's basically where my knowledge with respect to *ipconfig*, *TUN*, *TAP*, and IP routing/masquerading ends. I have the feeling that some setup step in the DigitalOcean guide hinders in multicast datagrams from my clients reaching the ReadyMedia service, e.g. maybe the *ipconfig* rule
```
# Allow traffic from OpenVPN client to wlp11s0 (change to the interface you discovered!)
-A POSTROUTING -s 10.8.0.0/8 -o wlp11s0 -j MASQUERADE
```
Also, I haven't figured out yet which the `10.0.0.0/8` OpenVPN server assigns to the Ubuntu machine itself - if at all such an IP is assigned.

Maybe you can already see what could be hindering in my setup, and that knowledge can then be incorporated into *vpnmcast*'s documentation in order for future users to pinpoint and resolve their issues. Thanks!

**Comment by danielkucera** [comment]
vpnmcast is not a solution for you because the multicast source is directly on vpn server. you should try adding a rule to route multicast to tun/tap device:
`route add 239.255.255.250 dev tun0`
