### ISSUE TITLE
Trying to test vpnmcast

### ISSUE THREAD

**Issue by bhamilton1co** [danielkucera/vpnmcast#6]
Here is what happens when I run ./vpnmcast.py

root@test-openvpn:/opt/vpnmcast# ./vpnmcast.py
Traceback (most recent call last):
  File "./vpnmcast.py", line 245, in <module>
    main()
  File "./vpnmcast.py", line 232, in main
    relay = Relay(dstif, senders)
  File "./vpnmcast.py", line 75, in __init__
    self.dest = self.raw_socket(iface)
  File "./vpnmcast.py", line 81, in raw_socket
    s.setsockopt(socket.SOL_SOCKET, 25, iface + '\0')
TypeError: a bytes-like object is required, not 'str'

Any ideas why the error? This is on a Debian 10 system.

**Comment by bhamilton1co** [comment]
root@test-openvpn:/opt/vpnmcast# python -V
Python 3.7.3

**Comment by bhamilton1co** [comment]
root@test-openvpn:/opt/vpnmcast# python -V
Python 3.7.3

**Comment by bhamilton1co** [comment]
vpnmcast.py seems to run if I run it using python2
Although it does not seem to achieve what I am hoping.
Clients are Yealink VOIP phones that connect to an OpenVPN server.
The OpenVPN server is configured in bridge mode using tap0 interface. (br0 bridges eth1 and tap0)
The PBX that needs to be able to see the Yealink phones is on same network as OpenVPN server.
Everything can communicate and ping and connect all directions, all on the same flat network 192.168.6.x
But the multicast packets do not seem to travel to and from the Yealink VOIP phones to and from the PBX, via OpenVPN server which is running vpnmcast.py
Everything else works fine. I have tried setting the sourceif & destifs to every possible combination.
Any ideas on what I'm missing?
